/**
 * Smart diff assembly — returns only salient data to the LLM.
 *
 * Strategies applied:
 *   1. Reduced context lines (git diff -U1 instead of default -U3)
 *   2. Auto-generated file suppression (lock files, .claude.json, dist/, etc.)
 *   3. Binary/minified detection and suppression
 *   4. Per-file budget: large changes (≥50 lines) get first hunk only
 *   5. Suppressed files listed so LLM can request full diff via `read` if needed
 */

import { git } from "./git.js";

// ── Auto-generated file patterns ────────────────────────────────────────────

const AUTOGEN_PATTERNS = [
  /\.claude\.json$/,
  /package-lock\.json$/,
  /yarn\.lock$/,
  /pnpm-lock\.yaml$/,
  /Gemfile\.lock$/,
  /Cargo\.lock$/,
  /poetry\.lock$/,
  /composer\.lock$/,
  /\.terraform\.lock\.hcl$/,
  /Pods\/Manifest\.lock$/,
  /\.generated\./,
  /\.min\.(js|css)$/,
  /\.map$/, // source maps
];

function isAutoGenerated(path: string): boolean {
  return AUTOGEN_PATTERNS.some((p) => p.test(path));
}

// ── Numstat parsing ─────────────────────────────────────────────────────────

interface FileStats {
  path: string;
  added: number;
  deleted: number;
}

function parseNumstat(output: string): FileStats[] {
  return output
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const parts = line.split("\t");
      const added = parts[0];
      const deleted = parts[1];
      // Handle renames: "{old => new}" or "old -> new"
      let path = parts.slice(2).join("\t");
      const arrow = path.indexOf(" => ");
      if (arrow >= 0) {
        // Extract the destination path from rename syntax
        const braceStart = path.lastIndexOf("{", arrow);
        const braceEnd = path.indexOf("}", arrow);
        if (braceStart >= 0 && braceEnd >= 0) {
          const prefix = path.slice(0, braceStart);
          const suffix = path.slice(braceEnd + 1);
          const newPart = path.slice(arrow + 4, braceEnd);
          path = prefix + newPart + suffix;
        } else {
          path = path.slice(arrow + 4);
        }
      }
      return {
        path,
        added: added === "-" ? 0 : parseInt(added ?? "0", 10),
        deleted: deleted === "-" ? 0 : parseInt(deleted ?? "0", 10),
      };
    });
}

// ── Diff splitting ──────────────────────────────────────────────────────────

/** Split a unified diff into per-file sections keyed by path */
function splitByFile(diff: string): Map<string, string> {
  const result = new Map<string, string>();
  if (!diff.trim()) return result;

  const parts = diff.split(/^(?=diff --git )/m);
  for (const part of parts) {
    if (!part.startsWith("diff --git")) continue;
    const match = part.match(/^diff --git a\/.+ b\/(.+)$/m);
    const path = match?.[1];
    if (path) result.set(path, part);
  }
  return result;
}

// ── Hunk extraction ─────────────────────────────────────────────────────────

/** Extract diff headers + first hunk, capped at maxLines of hunk content */
function firstHunk(content: string, maxLines: number): string {
  const lines = content.split("\n");
  const out: string[] = [];
  let inHunk = false;
  let hunkLines = 0;

  for (const line of lines) {
    // Always include file-level headers
    if (
      line.startsWith("diff --git") ||
      line.startsWith("index ") ||
      line.startsWith("--- ") ||
      line.startsWith("+++ ") ||
      line.startsWith("new file") ||
      line.startsWith("deleted file") ||
      line.startsWith("rename ")
    ) {
      out.push(line);
      continue;
    }
    // Hunk header
    if (line.startsWith("@@")) {
      if (inHunk) break; // second hunk → stop
      inHunk = true;
      out.push(line);
      continue;
    }
    if (inHunk) {
      out.push(line);
      hunkLines++;
      if (hunkLines >= maxLines) break;
    }
  }
  return out.join("\n");
}

// ── Minified detection ──────────────────────────────────────────────────────

const MINIFIED_LINE_THRESHOLD = 500;

function hasMinifiedContent(content: string): boolean {
  return content
    .split("\n")
    .some((l) => (l.startsWith("+") || l.startsWith("-")) && l.length > MINIFIED_LINE_THRESHOLD);
}

// ── Smart diff assembler ────────────────────────────────────────────────────

export interface SmartDiffResult {
  /** Filtered diff output (only salient content) */
  diff: string;
  /** Files suppressed with reason */
  suppressed: string[];
  /** Total files with changes */
  totalFiles: number;
  /** Files included in diff output */
  includedFiles: number;
}

export interface SmartDiffOptions {
  /** Lines changed threshold for "large file" (default: 50) */
  maxFileLines?: number;
  /** Max hunk lines shown for large files (default: 30) */
  maxHunkLines?: number;
}

/**
 * Assemble a smart diff from unstaged + staged changes.
 * Returns only salient content — auto-generated, binary, and minified files are suppressed.
 * Large files show only the first hunk.
 */
export async function assembleSmartDiff(
  cwd: string,
  signal?: AbortSignal,
  opts: SmartDiffOptions = {},
): Promise<SmartDiffResult> {
  const maxFileLines = opts.maxFileLines ?? 50;
  const maxHunkLines = opts.maxHunkLines ?? 30;

  // Parallel: get numstat + reduced-context diffs for both staged and unstaged
  const [numstatUnstaged, numstatStaged, diffUnstaged, diffStaged] = await Promise.all([
    git(["diff", "--numstat"], cwd, signal),
    git(["diff", "--staged", "--numstat"], cwd, signal),
    git(["diff", "-U1"], cwd, signal),
    git(["diff", "--staged", "-U1"], cwd, signal),
  ]);

  // Merge file stats (staged + unstaged)
  const statsMap = new Map<string, FileStats>();
  for (const info of [...parseNumstat(numstatStaged), ...parseNumstat(numstatUnstaged)]) {
    const existing = statsMap.get(info.path);
    if (existing) {
      existing.added += info.added;
      existing.deleted += info.deleted;
    } else {
      statsMap.set(info.path, { ...info });
    }
  }

  // Split diffs by file (staged first, unstaged appends)
  const fileDiffs = new Map<string, string>();
  for (const [path, content] of splitByFile(diffStaged)) fileDiffs.set(path, content);
  for (const [path, content] of splitByFile(diffUnstaged)) {
    const existing = fileDiffs.get(path);
    fileDiffs.set(path, existing ? `${existing}\n${content}` : content);
  }

  const included: string[] = [];
  const suppressed: string[] = [];

  for (const [path, content] of fileDiffs) {
    const stats = statsMap.get(path);
    const totalChanged = (stats?.added ?? 0) + (stats?.deleted ?? 0);

    // Binary?
    if (content.includes("Binary files")) {
      suppressed.push(`${path} (binary)`);
      continue;
    }

    // Auto-generated?
    if (isAutoGenerated(path)) {
      suppressed.push(`${path} (auto-generated, ${totalChanged} lines changed)`);
      continue;
    }

    // Minified?
    if (hasMinifiedContent(content)) {
      suppressed.push(`${path} (minified/long lines, ${totalChanged} lines changed)`);
      continue;
    }

    // Large file → first hunk only
    if (totalChanged >= maxFileLines) {
      const truncated = firstHunk(content, maxHunkLines);
      included.push(
        truncated +
          `\n... ${path}: ${totalChanged} lines changed, first hunk shown. Use \`read\` for full file.`,
      );
      continue;
    }

    // Small file → full diff
    included.push(content);
  }

  return {
    diff: included.join("\n") || "(no salient changes)",
    suppressed,
    totalFiles: fileDiffs.size,
    includedFiles: included.length,
  };
}
